# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rechubios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rechubios
  pod 'Starscream', '~> 3.0.4'
  pod 'Alamofire', '~> 4.7.0'
  pod 'MessageKit', '~> 3.0.0-swift5'
  pod 'SwiftyJSON', '~> 4.0'
  
  # target 'rechubiosTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
